### PR TITLE
Fix copy and paste mistake

### PR DESCRIPTION
**Pull request by illusionTBA**

### CODE REVIEW

**Comment by Nailington** [comment]
https://media.discordapp.net/attachments/1047253601413763092/1142911621455429692/watermark.gif

**Comment by illusionTBA** [comment]
stop framing me, i know you work for the CIA

**Comment by Nailington** [comment]
nuh uh

**Review by GreenyDEV — APPROVED** [review]

**Comment by GreenyDEV** [comment]
mf i know you did this to get on the contributor list lol

**Pull request merged**
