### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Thesecondalthowcool**

### CODE REVIEW

**Comment by Thesecondalthowcool** [comment]
Simple edits to make the frontpage look better

**Comment by FoxMoss** [comment]
please name your commits something useful

**Comment by CoolElectronics** [comment]
:fish:

**Comment by GreenyDEV** [comment]
fish

**Comment by FoxMoss** [comment]
:fish:

**Comment by Nailington** [comment]
:shrimp:

**Pull request closed without merging**
